# Generated by Django 5.2.1 on 2025-05-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('config_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('nginx', 'Nginx'), ('apache', 'Apache'), ('database', 'Databases'), ('security', 'Security'), ('network', 'Networking'), ('cicd', 'CI/CD'), ('terraform', 'Terraform'), ('ansible', 'Ansible'), ('other', 'Other')], default='other', max_length=50)),
                ('language', models.CharField(default='english', max_length=50)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
